### ISSUE TITLE
win11运行示例报错

### ISSUE THREAD

**Issue by thep0y** [element-plus/element-plus-vite-starter#33]
<details>
<summary>日志</summary>

```
 npm run dev

> element-plus-vite-starter@0.1.0 dev
> vite

Pre-bundling dependencies:
  vue
(this will be run only when your dependencies or config have changed)

  vite v2.8.6 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 516ms.

上午11:49:33 [vite] new dependencies found: element-plus/es, updating...
上午11:49:34 [vite] ✨ dependencies updated, reloading page...
上午11:49:35 [vite] Internal server error: Failed to resolve import "element-plus/es/components/menu/style/index" from "src\components\layouts\BaseHeader.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: M:/vue/element-plus-vite-starter/src/components/layouts/BaseHeader.vue
  1  |  /* unplugin-vue-components disabled */import { ElMenu as __unplugin_components_2 } from 'element-plus/es';import 'element-plus/es/components/menu/style/index';
     |                                                                                                                    ^
  2  |  import { ElSubMenu as __unplugin_components_1 } from 'element-plus/es';import 'element-plus/es/components/sub-menu/style/index';
  3  |  import { ElMenuItem as __unplugin_components_0 } from 'element-plus/es';import 'element-plus/es/components/menu-item/style/index';
      at formatError (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:38098:46)
      at TransformContext.error (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:38094:19)
      at normalizeUrl (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:69819:26)
      at async TransformContext.transform (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:69959:57)
      at async Object.transform (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:38334:30)
      at async doTransform (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:53030:29)
上午11:49:35 [vite] Internal server error: Failed to resolve import "element-plus/es/components/menu/style/index" from "src\components\layouts\BaseSide.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: M:/vue/element-plus-vite-starter/src/components/layouts/BaseSide.vue
  1  |  /* unplugin-vue-components disabled */import { ElMenu as __unplugin_components_4 } from 'element-plus/es';import 'element-plus/es/components/menu/style/index';
     |                                                                                                                    ^
  2  |  import { ElSubMenu as __unplugin_components_3 } from 'element-plus/es';import 'element-plus/es/components/sub-menu/style/index';
  3  |  import { ElMenuItemGroup as __unplugin_components_2 } from 'element-plus/es';import 'element-plus/es/components/menu-item-group/style/index';
      at formatError (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:38098:46)
      at TransformContext.error (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:38094:19)
      at normalizeUrl (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:69819:26)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:69959:57)
      at async Object.transform (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:38334:30)
      at async doTransform (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:53030:29)
上午11:49:35 [vite] Internal server error: Failed to resolve import "element-plus/es/components/date-picker/style/index" from "src\components\HelloWorld.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: M:/vue/element-plus-vite-starter/src/components/HelloWorld.vue
  1  |  /* unplugin-vue-components disabled */import { ElDatePicker as __unplugin_components_3 } from 'element-plus/es';import 'element-plus/es/components/date-picker/style/index';
     |                                                                                                                          ^
  2  |  import { ElTag as __unplugin_components_2 } from 'element-plus/es';import 'element-plus/es/components/tag/style/index';
  3  |  import { ElInput as __unplugin_components_1 } from 'element-plus/es';import 'element-plus/es/components/input/style/index';
      at formatError (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:38098:46)
      at TransformContext.error (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:38094:19)
      at normalizeUrl (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:69819:26)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:69959:57)
      at async Object.transform (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:38334:30)
      at async doTransform (M:\vue\element-plus-vite-starter\node_modules\vite\dist\node\chunks\dep-9c153816.js:53030:29)
```
</details>

**Comment by sxzz** [comment]
Please provide a minimum reproduction link.

**Comment by YunYouJun** [comment]
Can not reproduce, are you sure you have updated to the latest version template?

**Comment by thep0y** [comment]
没有特别的复现步骤，克隆此仓库后npm i安装依赖，npm run dev后打开:3000就出现这个问题发自我的手机-------- 原始邮件 --------发件人： 三咲智子 ***@***.***>日期： 2022年3月12日周六 12:52收件人： element-plus/element-plus-vite-starter ***@***.***>抄送： thep0y ***@***.***>, Author ***@***.***>主    题： Re: [element-plus/element-plus-vite-starter] win11运行示例报错 (Issue #33)
Please provide a minimum reproduction link.

**Comment by thep0y** [comment]
> Can not reproduce, are you sure you have updated to the latest version template?

Yes, I cloned the latest template this morning.

**Comment by YunYouJun** [comment]
Please `rm -rf node_modules` and `pnpm i element-plus@2.0.5 && pnpm i`.

It seems caused by wrong package of `v2.0.6`.

**Comment by aStudyingTurtle** [comment]
The same error on Ubuntu20.04 and windows10.
And `rm -rf node_modules and pnpm i element-plus@2.0.5 && pnpm i.` can help.
Thank you.
[plugin:vite:import-analysis] Failed to resolve import "element-plus/es/components/menu/style/index" from "src/components/layouts/BaseHeader.vue". Does the file exist?
[/home/xuan/element-plus-vite-starter/src/components/layouts/BaseHeader.vue:1:115]()
1  |  /* unplugin-vue-components disabled */import { ElMenu as __unplugin_components_2 } from 'element-plus/es';import 'element-plus/es/components/menu/style/index';
   |                                                                                                                    ^
2  |  import { ElSubMenu as __unplugin_components_1 } from 'element-plus/es';import 'element-plus/es/components/sub-menu/style/index';
3  |  import { ElMenuItem as __unplugin_components_0 } from 'element-plus/es';import 'element-plus/es/components/menu-item/style/index';
    at formatError ([/home/xuan/element-plus-vite-starter/node_modules/vite/dist/node/chunks/dep-9c153816.js:38098:46]())
    at TransformContext.error ([/home/xuan/element-plus-vite-starter/node_modules/vite/dist/node/chunks/dep-9c153816.js:38094:19]())
    at normalizeUrl ([/home/xuan/element-plus-vite-starter/node_modules/vite/dist/node/chunks/dep-9c153816.js:69819:26]())
    at async TransformContext.transform ([/home/xuan/element-plus-vite-starter/node_modules/vite/dist/node/chunks/dep-9c153816.js:69959:57]())
    at async Object.transform ([/home/xuan/element-plus-vite-starter/node_modules/vite/dist/node/chunks/dep-9c153816.js:38334:30]())
    at async doTransform ([/home/xuan/element-plus-vite-starter/node_modules/vite/dist/node/chunks/dep-9c153816.js:53030:29]()
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

**Comment by sxzz** [comment]
Please try `2.1.0`
