### ISSUE TITLE
运行 vite-ssg build 报错 ReferenceError: document is not defined

### ISSUE THREAD

**Issue by Alex6357** [element-plus/element-plus-vite-starter#77]
最开始遇到报错 `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".scss"`，根据 vuejs/vitepress#3713 添加

```
ssr: {
  noExternal: ['element-plus']
}
```

现在遇到这样的报错

```
PS F:\try\element-plus-vite-starter> pnpm generate

> element-plus-vite-starter@0.1.0 generate F:\try\element-plus-vite-starter
> vite-ssg build


[vite-ssg] Build for client...
vite v5.4.11 building for production...
✓ 1465 modules transformed.
dist/index.html                 0.63 kB │ gzip:   0.39 kB
dist/.vite/ssr-manifest.json   42.04 kB │ gzip:   2.89 kB
dist/assets/app-Cq6zJ6Ll.css   91.55 kB │ gzip:  14.14 kB
dist/assets/app-CKkIQwRy.js   331.61 kB │ gzip: 112.61 kB
✓ built in 5.21s

[vite-ssg] Build for server...
vite v5.4.11 building SSR bundle for production...
✓ 775 modules transformed.
.vite-ssg-temp/7vus7onjbu/assets/style-CmMWDdb5.css  108.40 kB
.vite-ssg-temp/7vus7onjbu/main.mjs                   418.34 kB
✓ built in 2.89s

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
F:\try\element-plus-vite-starter\node_modules\.pnpm\@vue+runtime-dom@3.5.13\node_modules\@vue\runtime-dom\dist\runtime-dom.cjs.prod.js:1631
    const res = document.querySelector(container);
                ^

ReferenceError: document is not defined
    at normalizeContainer (F:\try\element-plus-vite-starter\node_modules\.pnpm\@vue+runtime-dom@3.5.13\node_modules\@vue\runtime-dom\dist\runtime-dom.cjs.prod.js:1631:17)
    at app.mount (F:\try\element-plus-vite-starter\node_modules\.pnpm\@vue+runtime-dom@3.5.13\node_modules\@vue\runtime-dom\dist\runtime-dom.cjs.prod.js:1592:23)
    at file:///F:/try/element-plus-vite-starter/.vite-ssg-temp/7vus7onjbu/main.mjs:12118:5
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async build (file:///F:/try/element-plus-vite-starter/node_modules/.pnpm/vite-ssg@0.23.8_vite@5.4.11_@types+node@20.17.6_sass@1.81.0_terser@5.36.0__vue@3.5.13_typescript@5.6.3_/node_modules/vite-ssg/dist/node.mjs:999:87)
    at async Object.handler (file:///F:/try/element-plus-vite-starter/node_modules/.pnpm/vite-ssg@0.23.8_vite@5.4.11_@types+node@20.17.6_sass@1.81.0_terser@5.36.0__vue@3.5.13_typescript@5.6.3_/node_modules/vite-ssg/dist/node/cli.mjs:34:5)

Node.js v22.11.0
 ELIFECYCLE  Command failed with exit code 1.
```

我不清楚这个 issue 应该提到哪里，暂时提交到这里，希望指点

**Comment by YunYouJun** [comment]
此前没有添加 vite-ssg 的入口示例，已添加。
